services:
  - type: web
    name: fastapi-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn assets.main:app --host 0.0.0.0 --port $PORT
    plan: free
    autoDeploy: true